version: '3.8'
name: challenge-bsale

services:
    bsale-mysql:
        container_name: bsale-mysql
        restart: always
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: bsale_test_root
            MYSQL_USER: bsale_test
            MYSQL_PASSWORD: bsale_test
            MYSQL_DATABASE: airline
        volumes:
            - ./airline.sql:/docker-entrypoint-initdb.d/airline.sql
        ports:
            - '3306:3306'

    bsale-server:
        container_name: bsale-server
        restart: unless-stopped
        image: bsale-server
        environment:
            DATABASE_URL: mysql://bsale_test:bsale_test@bsale-mysql:3306/airline?allowPublicKeyRetrieval=true&useSSL=false
            PORT: 3000
        ports:
            - '3000:3000'
        build:
            context: .
        depends_on:
            - bsale-mysql
